import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import { cn } from "../lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body
      className={cn(
        "min-h-screen w-full bg-white text-black flex ",
        inter.className,
        {
          "debug-screens": process.env.NODE_ENV === "development"
        }
      )}
    >
      {/* sidebar */}
      {/* <p className="border">Sidebar</p> */}
      <Sidebar />
      {/* main page */}
      <div className="p-8 w-full">{children}</div>
    </body>
  </html>
  );
}
